from __future__ import annotations

import contextlib
import json
import logging
import threading
import time
from copy import deepcopy
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Literal, Optional, Union

import matplotlib.pyplot as plt
import numpy as np
from grpclib.exceptions import StreamTerminatedError
from matplotlib.gridspec import GridSpec
from octave_sdk import RFOutputMode, OctaveLOSource
from qm import QuantumMachinesManager, SimulationConfig, generate_qua_script, qua, QuantumMachine
from qm.jobs.running_qm_job import RunningQmJob
from qm.simulate import SimulatorControllerSamples, SimulatorSamples
from tqdm import tqdm

from .analysis.analysis_tools import Output
from .analysis.post_process import proc_default
from qubox.pulse_manager import PulseOperationManager

# ────────────────────────────── Logging & Errors ──────────────────────────────
_logger = logging.getLogger(__name__)


class QMError(RuntimeError): ...
class QMConfigError(QMError): ...
class QMConnectionError(QMError): ...
class QMJobError(QMError): ...


# QM config keys (full schema)
_QM_TOPLEVEL_WHITELIST = {
    "version", "controllers", "elements", "octaves",
    "mixers", "waveforms", "digital_waveforms",
    "integration_weights", "oscillators", "pulses",
}

# “hardware.json skeleton” keys (persisted)
_HARDWARE_TOPLEVEL_KEYS = {
    "version",
    "controllers",
    "octaves",
    "elements",
}

# keys that are "pulses overlay" (generated by POM)
_PULSE_KEYS = {
    "pulses",
    "waveforms",
    "digital_waveforms",
    "integration_weights",
    "mixers",
    "oscillators",
}

# extras you want to persist with hardware.json
_HARDWARE_EXTRAS_KEYS_DEFAULT = {"octave_links", "__qubox"}

# Default plotting behavior for simulate()
_DEFAULT_PLOT_PARAMS: Dict[str, Any] = {
    "which": "both",
    "channels": None,
    "time_unit": "ns",
    "xlim": None,
    "ylim": None,
    "digital_ylim": None,
    "title": None,
    "legend": True,
    "grid": True,
}


def _key_like(d: dict, k: int | str) -> int | str:
    """
    Return the key in `d` that corresponds to `k`, handling "3" vs 3.
    If no match exists, returns `k` unchanged (caller may create new entry).
    """
    if k in d:
        return k
    if isinstance(k, int) and str(k) in d:
        return str(k)
    if isinstance(k, str) and k.isdigit() and int(k) in d:
        return int(k)
    return k


def _get_nested(d: dict, path: list, default=None):
    cur = d
    for p in path:
        if not isinstance(cur, dict) or p not in cur:
            return default
        cur = cur[p]
    return cur


def _filter_qm_schema(d: dict) -> dict:
    return {k: deepcopy(v) for k, v in d.items() if k in _QM_TOPLEVEL_WHITELIST}


def _filter_hardware_schema(d: dict) -> dict:
    return {k: deepcopy(v) for k, v in d.items() if k in _HARDWARE_TOPLEVEL_KEYS}


def _select_keys(d: dict, keys: set[str]) -> dict:
    return {k: deepcopy(v) for k, v in d.items() if k in keys}


def _require(cond: bool, msg: str, exc=QMConfigError):
    if not cond:
        raise exc(msg)


# ─────────────────────────────────── Helpers ──────────────────────────────────
def _numeric_keys_to_ints(obj):
    if isinstance(obj, dict):
        return {
            (int(k) if isinstance(k, str) and k.isdigit() else k): _numeric_keys_to_ints(v)
            for k, v in obj.items()
        }
    if isinstance(obj, list):
        return [_numeric_keys_to_ints(v) for v in obj]
    return obj


def _json_dump(obj, **kw) -> str:
    def _default(o):
        if isinstance(o, (np.floating, np.integer)):
            return o.item()
        if isinstance(o, np.ndarray):
            return o.tolist()
        raise TypeError(f"Unserializable: {type(o)}")

    return json.dumps(obj, default=_default, **kw)


def _with_retries(fn: Callable, *, attempts=3, backoff=0.5, exc_types: tuple = (StreamTerminatedError,)):
    for k in range(attempts):
        try:
            return fn()
        except exc_types as e:
            if k == attempts - 1:
                raise
            sleep_s = backoff * (2 ** k)
            _logger.warning(f"Transient error ({e}); retrying in {sleep_s:.2f}s...")
            time.sleep(sleep_s)


def _prog_flag(prog, name: str, default=None):
    return getattr(prog, name, default)


def _deep_merge(dst: dict, src: dict) -> dict:
    """
    Deep merge dicts: returns new dict (does not mutate inputs).
    - If both values are dicts, merges recursively.
    - Otherwise src overwrites dst.
    """
    out = deepcopy(dst)
    for k, v in (src or {}).items():
        if k in out and isinstance(out[k], dict) and isinstance(v, dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = deepcopy(v)
    return out


ModeLike = Union["RFOutputMode", str, Literal["keep_hw"]]

_JSON_MODE_MAP = {
    RFOutputMode.on: "always_on",
    RFOutputMode.off: "always_off",
    RFOutputMode.trig_normal: "triggered",
    RFOutputMode.trig_inverse: "triggered_reversed",
    RFOutputMode.debug: "always_off",  # safe fallback for JSON
}

_LO_SOURCE_MAP: Dict[str, OctaveLOSource] = {
    "internal": OctaveLOSource.Internal,
    "lo1": OctaveLOSource.LO1,
    "lo2": OctaveLOSource.LO2,
    "lo3": OctaveLOSource.LO3,
    "lo4": OctaveLOSource.LO4,
    "lo5": OctaveLOSource.LO5,
}


def _patch_octave_output_modes_in_json(cfg: dict, mode: RFOutputMode) -> None:
    str_mode = _JSON_MODE_MAP[mode]
    for _, oct_data in (cfg.get("octaves") or {}).items():
        rf_outs = oct_data.get("RF_outputs") or {}
        for _, ch_data in rf_outs.items():
            if isinstance(ch_data, dict):
                ch_data["output_mode"] = str_mode

class ExecMode(str, Enum):
    HARDWARE = "hardware"
    SIMULATE = "simulate"

def _coerce_exec_mode(mode: ExecMode | str | None) -> ExecMode:
    if mode is None:
        return ExecMode.HARDWARE
    if isinstance(mode, ExecMode):
        return mode
    s = str(mode).strip().lower()
    if s in ("hardware", "hw"):
        return ExecMode.HARDWARE
    if s in ("simulate", "sim"):
        return ExecMode.SIMULATE
    raise ValueError(f"Unknown ExecMode: {mode!r}")


@dataclass
class RunResult:
    mode: "ExecMode"
    output: Output
    sim_samples: Optional[Any] = None
    metadata: dict | None = None


# ───────────────────────────────── Main Manager ───────────────────────────────
class QuaProgramManager:
    """
    Refactor summary:
      - hardware_base + hardware_extras are the persisted truth (hardware.json)
      - pulse_overlay is generated (pulses/waveforms/weights/etc)
      - runtime_overrides are ephemeral patches you may or may not persist
      - qm_config is an artifact built by build_qm_config()
      - apply_changes() rebuilds + reopens QM (the “burn” operation)
    """

    # ───────────────────────────── init ─────────────────────────────
    def __init__(
        self,
        qop_ip: str,
        cluster_name: str,
        oct_cal_path: str,
        *,
        hardware_path: str | Path | None = None,
        config_dict: dict | None = None,
        default_output_mode: ModeLike = "on",
        override_octave_json_mode: Optional[ModeLike] = None,
        hardware_extras_keys: Optional[set[str]] = None,
    ):
        self._qmm = QuantumMachinesManager(
            host=qop_ip,
            cluster_name=cluster_name,
            octave_calibration_db_path=oct_cal_path,
        )
        self.qm: QuantumMachine | None = None
        self.job: Optional[RunningQmJob] = None
        self._lock = threading.RLock()

        # Persisted IO
        self.hardware_path: Optional[Path] = Path(hardware_path) if hardware_path else None
        self._hardware_extras_keys = set(_HARDWARE_EXTRAS_KEYS_DEFAULT if hardware_extras_keys is None else hardware_extras_keys)

        # Layered state
        self.hardware_base: dict | None = None
        self.hardware_extras: dict = {}
        self.pulse_overlay: dict = {}
        self.element_ops_overlay: dict = {}
        self.runtime_overrides: dict = {}
        self.qm_config: dict | None = None

        self._dirty: dict[str, bool] = {"hardware": False, "pulses": False, "runtime": False}

        # book-keeping
        self.config_exists = False
        self.elements: Dict[str, Dict] = {}
        self.processors: List[Callable] = [proc_default]
        self.spa_pump_sc = None
        self._device_manager = None                  # optional DeviceManager for external LO sources
        self.current_program = None                  # backward-compat alias: "most recently submitted/run/simulated"
        self._last_program_cfg: dict | None = None   # config snapshot used for last program
        self._last_program_meta: dict = {}           # optional metadata (mode, queued, timestamps, job_id...)
        self._last_program_ts: float | None = None

        # output-mode preferences
        self._default_output_mode: RFOutputMode | None = self._coerce_rf_mode(default_output_mode)
        self._override_octave_json_mode: RFOutputMode | None = self._coerce_rf_mode(override_octave_json_mode)

        # Load hardware.json (if provided)
        self.load_hardware(self.hardware_path)

        # Optional: allow constructing from a provided full QM config
        if config_dict is not None:
            cfg = _numeric_keys_to_ints(_filter_qm_schema(config_dict))
            self.hardware_base = _filter_hardware_schema(cfg)
            self.hardware_extras = _select_keys(config_dict, self._hardware_extras_keys)
            self.pulse_overlay = {k: deepcopy(cfg.get(k, {})) for k in _PULSE_KEYS if k in cfg}
            self.runtime_overrides = {}
            self._dirty = {"hardware": False, "pulses": False, "runtime": False}

        if self.hardware_base is not None or config_dict is not None:
            self.apply_changes(save_hardware=False, allow_while_running=True)

        self.exec_mode: ExecMode = ExecMode.HARDWARE


    # ─────────────────────────── internal guards ──────────────────────
    def _remember_program(self, qua_prog, *, cfg: dict | None = None, meta: dict | None = None) -> None:
        """
        Record the most recent program and (optionally) a snapshot of the config used.
        This is what serialize_program() will use by default.
        """
        with self._lock:
            self.current_program = qua_prog
            self._last_program_ts = time.time()
            if cfg is not None:
                self._last_program_cfg = deepcopy(cfg)
            if meta:
                self._last_program_meta = {**self._last_program_meta, **deepcopy(meta)}


    def _require_qm(self):
        _require(self.qm is not None, "QM not initialized; call apply_changes() or init_qm().", QMError)

    def _check_el(self, el: str):
        _require(el in self.elements, f"Unknown element '{el}'", QMConfigError)

    @staticmethod
    def _coerce_rf_mode(mode: Optional[ModeLike]) -> Optional[RFOutputMode]:
        if mode is None or isinstance(mode, RFOutputMode):
            return mode
        return {
            "on": RFOutputMode.on,
            "off": RFOutputMode.off,
            "debug": RFOutputMode.debug,
            "trig_normal": RFOutputMode.trig_normal,
            "trig_inverse": RFOutputMode.trig_inverse,
        }.get(mode)

    # ────────────────────────── external controls ─────────────────────
    def set_spa_pump(self, spa_pump_sc):
        self.spa_pump_sc = spa_pump_sc

    def set_device_manager(self, dm) -> None:
        self._device_manager = dm

    # ────────────────────────── external LO helpers ──────────────────
    def _element_octave_rf_out(self, el: str) -> tuple[str, int] | None:
        """Return (octave_name, rf_out_port) for an element, or None."""
        cfg = self.qm_config or {}
        el_cfg = (cfg.get("elements") or {}).get(el)
        if not isinstance(el_cfg, dict):
            return None
        rf_in = el_cfg.get("RF_inputs")
        if not isinstance(rf_in, dict):
            return None
        port = rf_in.get("port")
        if isinstance(port, (list, tuple)) and len(port) >= 2:
            return (str(port[0]), int(port[1]))
        return None

    def _is_external_lo(self, el: str) -> bool:
        """True if the element's octave RF output uses an external LO source."""
        tup = self._element_octave_rf_out(el)
        if tup is None:
            return False
        octave_name, rf_port = tup
        cfg = self.qm_config or {}
        rf_outs = _get_nested(cfg, ["octaves", octave_name, "RF_outputs"], {})
        if not isinstance(rf_outs, dict):
            return False
        k = _key_like(rf_outs, rf_port)
        ch = rf_outs.get(k)
        if isinstance(ch, dict):
            return str(ch.get("LO_source", "")).lower() == "external"
        return False

    def _external_lo_info(self, el: str) -> dict | None:
        """
        Return external LO info dict for an element, or None.

        Reads __qubox.external_lo_map in hardware_extras, keyed by "octave:rf_out".

        Supports two formats:
        - Legacy string:  "oct1:2": "device_name"           → {"device": "device_name"}
        - Dict (preferred): "oct1:2": {"device": "...", "lo_port": "LO2"}
        """
        tup = self._element_octave_rf_out(el)
        if tup is None:
            return None
        octave_name, rf_port = tup
        qubox = (self.hardware_extras or {}).get("__qubox") or {}
        lo_map = qubox.get("external_lo_map") or {}
        entry = lo_map.get(f"{octave_name}:{rf_port}")
        if entry is None:
            return None
        if isinstance(entry, str):
            # Legacy format: just the device name
            return {"device": entry}
        if isinstance(entry, dict):
            return entry
        return None

    def _external_lo_device_name(self, el: str) -> str | None:
        """Return the DeviceManager device name for an element's external LO, or None."""
        info = self._external_lo_info(el)
        return info.get("device") if info else None

    @staticmethod
    def _parse_lo_source(s: str) -> OctaveLOSource | None:
        """Parse a string like 'LO2' into the corresponding OctaveLOSource enum value."""
        return _LO_SOURCE_MAP.get(s.lower().strip())

    def _configure_lo_source(self, el: str) -> None:
        """
        Tell the Octave which physical LO input port to route for an external-LO element.

        Per QM Octave docs: "LO source number must correspond to the up converter module number."
        E.g. RF output 2 must use OctaveLOSource.LO2.
        """
        info = self._external_lo_info(el)
        if info is None:
            return

        lo_port_str = info.get("lo_port")
        if lo_port_str is None:
            _logger.warning(
                f"No lo_port specified in external_lo_map for element '{el}'; "
                f"skipping set_lo_source. Add 'lo_port': 'LO2' (etc.) to the map entry."
            )
            return

        lo_port = self._parse_lo_source(lo_port_str)
        if lo_port is None:
            _logger.warning(
                f"Unknown lo_port '{lo_port_str}' for element '{el}'; "
                f"valid values: {list(_LO_SOURCE_MAP.keys())}. Skipping set_lo_source."
            )
            return

        self.qm.octave.set_lo_source(el, lo_port)
        _logger.info(f"set LO source for element '{el}' to {lo_port.name}")

    # ─────────────────────────── Hardware I/O ─────────────────────────
    def load_hardware(self, hardware_path: str | Path | None) -> None:
        hp = Path(hardware_path) if hardware_path else None
        if hp is not None:
            self.hardware_path = hp

        self.hardware_base = None
        self.hardware_extras = {}
        self._dirty["hardware"] = False

        if not self.hardware_path or not self.hardware_path.exists():
            _logger.info("No hardware file provided/found; continuing without hardware.")
            return

        raw = _numeric_keys_to_ints(json.loads(self.hardware_path.read_text()))
        self.hardware_base = _filter_hardware_schema(raw)
        self.hardware_extras = _select_keys(raw, self._hardware_extras_keys)
        _logger.info(f"Hardware loaded from {self.hardware_path}")

    def save_hardware(self, path: str | Path | None = None):
        _require(self.hardware_base is not None, "No hardware loaded to save.")
        dst = Path(path) if path else (self.hardware_path or Path("hardware.json"))
        to_write = {**deepcopy(self.hardware_base), **deepcopy(self.hardware_extras)}
        dst.write_text(_json_dump(to_write, indent=2))
        _logger.info(f"hardware saved → {dst}")
        self._dirty["hardware"] = False

    # ───────────────────────── Layered build/apply ─────────────────────
    def build_qm_config(self) -> dict:
        _require(self.hardware_base is not None, "No hardware loaded; cannot build QM config.")

        cfg = deepcopy(self.hardware_base)

        # Merge pulse overlay (top-level pulse blocks overwrite)
        if self.pulse_overlay:
            for k, v in self.pulse_overlay.items():
                cfg[k] = deepcopy(v)

        # Merge element operations overlay (deep merge so we don't clobber elements definitions)
        if self.element_ops_overlay:
            cfg = _deep_merge(cfg, self.element_ops_overlay)

        # Runtime overrides deep-merge (ephemeral patches)
        if self.runtime_overrides:
            cfg = _deep_merge(cfg, self.runtime_overrides)

        cfg = _numeric_keys_to_ints(cfg)
        cfg = _filter_qm_schema(cfg)

        if self._override_octave_json_mode is not None:
            _patch_octave_output_modes_in_json(cfg, self._override_octave_json_mode)

        return cfg


    def apply_changes(
        self,
        *,
        save_hardware: bool = False,
        allow_while_running: bool = False,
        stop_job: bool = True,
        init_elements: bool = True,
    ):
        with self._lock:
            if self.job and stop_job and not allow_while_running:
                with contextlib.suppress(Exception):
                    self.halt_job()

            new_cfg = self.build_qm_config()
            self.launch_qm(new_cfg)

            if init_elements:
                self.elements = self._init_elements()

            self.qm_config = new_cfg
            self._dirty = {"hardware": False, "pulses": False, "runtime": False}

            if save_hardware:
                self.save_hardware()

    def patch_hardware(
        self,
        patch_fn: Callable[[dict, dict], None],
        *,
        autosave: bool = False,
        autoburn: bool = True,
        allow_while_running: bool = False,
    ):
        _require(self.hardware_base is not None, "No hardware loaded; cannot patch.")
        _require(callable(patch_fn), "patch_fn must be callable")

        patch_fn(self.hardware_base, self.hardware_extras)
        self._dirty["hardware"] = True

        if autoburn:
            self.apply_changes(save_hardware=autosave, allow_while_running=allow_while_running)
        elif autosave:
            self.save_hardware()

    def patch_runtime(
        self,
        overrides: dict,
        *,
        autoburn: bool = True,
        allow_while_running: bool = False,
    ):
        _require(isinstance(overrides, dict), "overrides must be a dict")
        self.runtime_overrides = _deep_merge(self.runtime_overrides, overrides)
        self._dirty["runtime"] = True
        if autoburn:
            self.apply_changes(save_hardware=False, allow_while_running=allow_while_running)

    def clear_runtime_overrides(self, *, autoburn: bool = True):
        self.runtime_overrides = {}
        self._dirty["runtime"] = False
        if autoburn:
            self.apply_changes(save_hardware=False, allow_while_running=True)

    # ────────────────────── Pulses merger entry point ───────────────────
    def merge_pulses(self, pom: PulseOperationManager, *, include_volatile: bool = True, autoburn: bool = True):
        """
        Generate pulse overlay from POM without mutating persisted hardware.

        Also captures elements[*].operations injected by POM and stores it as a deep-merge overlay.
        """
        _require(self.hardware_base is not None, "Hardware is unknown; call load_hardware().")

        cfg = deepcopy(self.hardware_base)
        pom.burn_to_config(cfg, include_volatile=include_volatile)

        # store only generated top-level pulse blocks
        self.pulse_overlay = {k: deepcopy(cfg.get(k, {})) for k in _PULSE_KEYS}

        # store element operations as a *deep merge patch* so we don't clobber elements
        elems = cfg.get("elements") or {}
        ops_patch: dict = {}
        for el, el_cfg in elems.items():
            if not isinstance(el_cfg, dict):
                continue
            ops = el_cfg.get("operations")
            if isinstance(ops, dict) and ops:
                ops_patch.setdefault(el, {})["operations"] = deepcopy(ops)

        self.element_ops_overlay = {"elements": ops_patch} if ops_patch else {}

        self._dirty["pulses"] = True
        _logger.info("pulses merged into pulse_overlay (and element operations captured)")

        if autoburn:
            self.apply_changes(save_hardware=False, allow_while_running=True)


    def burn_pulse_to_qm(self, pom: PulseOperationManager | None = None, *, include_volatile: bool = True):
        if pom is not None:
            self.merge_pulses(pom, include_volatile=include_volatile, autoburn=True)
        else:
            self.apply_changes(save_hardware=False, allow_while_running=True)

    # ───────────────────────── existing API (updated) ────────────────
    def init_qm(self, config_dict: dict | None = None, *, init_elements: bool = True):
        if config_dict is not None:
            self.launch_qm(config_dict)
            if init_elements:
                self.elements = self._init_elements()
            return
        self.apply_changes(save_hardware=False, allow_while_running=True, init_elements=init_elements)

    def launch_qm(self, config_dict: dict, *, close_other_machines: bool = True):
        with self._lock:
            cfg_qm = _filter_qm_schema(_numeric_keys_to_ints(config_dict))
            try:
                self.qm = _with_retries(
                    lambda: self._qmm.open_qm(cfg_qm, close_other_machines=bool(close_other_machines))
                )
            except StreamTerminatedError as e:
                raise QMConnectionError("open_qm failed repeatedly.") from e

            self.qm_config = cfg_qm
            self.config_exists = True
            _logger.info("QM opened with provided configuration.")


    # ───────────────────────── Element alias helpers ───────────────────
    def _octave_links(self) -> list[dict]:
        ex = self.hardware_extras or {}
        if "octave_links" in ex:
            return list(ex["octave_links"] or [])
        qubox = ex.get("__qubox") or {}
        return list(qubox.get("octave_links") or [])

    def _build_ao_aliases_from_config(self) -> Dict[str, Dict[str, str]]:
        cfg = self.qm_config or {}
        elements = cfg.get("elements", {}) or {}
        links = self._octave_links()

        rf_to_ao: Dict[tuple[str, int], tuple[str, int, int]] = {}
        for it in links:
            try:
                rf_to_ao[(str(it["octave"]), int(it["rf_out"]))] = (
                    str(it["controller"]), int(it["ao_i"]), int(it["ao_q"])
                )
            except Exception:
                continue

        per_ctrl_alias: Dict[str, Dict[str, str]] = {}
        for el_name, el in elements.items():
            rf_in = el.get("RF_inputs")
            if not isinstance(rf_in, dict):
                continue
            port = rf_in.get("port")
            if not (isinstance(port, (list, tuple)) and len(port) >= 2):
                continue

            tup = rf_to_ao.get((str(port[0]), int(port[1])))
            if not tup:
                continue

            ctrl, ao_i, ao_q = tup
            m = per_ctrl_alias.setdefault(ctrl, {})
            m[f"1-{ao_i}"] = f"{el_name}:I"
            m[f"1-{ao_q}"] = f"{el_name}:Q"
        return per_ctrl_alias

    def _build_do_aliases_from_config(self) -> Dict[str, Dict[str, str]]:
        cfg = self.qm_config or {}
        elements = cfg.get("elements", {}) or {}
        per_ctrl_alias: Dict[str, Dict[str, str]] = {}
        for el_name, el in elements.items():
            for label, meta in (el.get("digitalInputs") or {}).items():
                port = meta.get("port")
                if not (isinstance(port, (list, tuple)) and len(port) >= 2):
                    continue
                ctrl, dport = str(port[0]), int(port[1])
                per_ctrl_alias.setdefault(ctrl, {})[f"1-{dport}"] = f"{el_name}:{label}"
        return per_ctrl_alias

    def _relabel_simulator_samples(self, sim) -> "SimulatorSamples":
        ao_aliases = self._build_ao_aliases_from_config()
        do_aliases = self._build_do_aliases_from_config()
        relabeled_by_ctrl = {}
        for ctrl, con in sim.items():
            a_alias = ao_aliases.get(ctrl, {})
            d_alias = do_aliases.get(ctrl, {})

            analog_new, sr_new = {}, {}
            for raw_key, arr in con.analog.items():
                new_key = a_alias.get(raw_key, raw_key)
                analog_new[new_key] = arr
                sr_new[new_key] = con.analog_sampling_rate.get(str(raw_key), 1e9)

            digital_new = {d_alias.get(k, k): v for k, v in con.digital.items()}

            relabeled_by_ctrl[ctrl] = SimulatorControllerSamples(
                analog=analog_new,
                digital=digital_new,
                analog_sampling_rate=sr_new,
            )
        return SimulatorSamples(relabeled_by_ctrl)

    # ───────────────────────── Init & calibration ──────────────────────
    def init_config(self, output_mode: RFOutputMode | None = None):
        self._require_qm()
        mode = output_mode if output_mode is not None else self._default_output_mode
        _logger.info("Initializing Default Element Configurations")
        for el in self.qm.get_config().get("elements", {}):
            if el.startswith("__"):
                continue
            # Configure external LO source routing before setting frequency
            if self._is_external_lo(el):
                self._configure_lo_source(el)
            self.set_element_lo(el, self.get_element_lo(el))
            if mode is not None:
                self.set_octave_output(el, mode)
            _logger.info("-" * 37)

    def _init_elements(self) -> Dict[str, Dict[str, float]]:
        self._require_qm()
        cfg = self.qm.get_config()
        elems: Dict[str, Dict[str, float]] = {}
        for el, info in (cfg.get("elements") or {}).items():
            if el.startswith("__"):
                continue
            lo_freq = None
            if "mixInputs" in info:
                lo_freq = info["mixInputs"].get("lo_frequency")
            elif "singleInput" in info:
                lo_freq = info["singleInput"].get("lo_frequency")
            if_freq = info.get("intermediate_frequency", 0.0)
            if lo_freq is None:
                _logger.warning(f"Element '{el}' has no LO frequency in config; setting LO=None")
            elems[el] = {"LO": lo_freq, "IF": if_freq}
        return elems

    def register_processor(self, processor: Callable[[Output], Output]):
        _require(callable(processor), "processor must be callable")
        self.processors.append(processor)

    # ───────────────────────── Live hardware commands ──────────────────
    def set_element_lo(self, el: str, el_lo: float):
        self._require_qm()
        self._check_el(el)

        if self._is_external_lo(el):
            # External LO: use DeviceManager to set frequency on the SignalCore (or similar)
            dev_name = self._external_lo_device_name(el)
            if dev_name and self._device_manager is not None:
                self._device_manager.apply(dev_name, frequency=int(el_lo))
                _logger.info(f"set external LO for element {el} via device '{dev_name}' to {el_lo * 1e-9:.6f} GHz")
            else:
                _logger.warning(
                    f"Element '{el}' uses an external LO but no DeviceManager or mapping is available "
                    f"(device_name={dev_name!r}, device_manager={'set' if self._device_manager else 'None'}). "
                    f"Skipping hardware LO set; updating internal bookkeeping only."
                )
        else:
            self.qm.octave.set_lo_frequency(el, el_lo)
            _logger.info(f"set LO for element {el} to {el_lo * 1e-6:.3f} MHz")

        self.elements[el]["LO"] = el_lo

    def set_element_fq(self, el: str, freq: float):
        self._require_qm()
        self._check_el(el)
        if_freq = self.calculate_el_if_fq(el, freq)
        self.qm.set_intermediate_frequency(el, if_freq)
        self.elements[el]["IF"] = if_freq
        _logger.info(f"Set element {el} to frequency: {freq * 1e-6:.3f} MHz -> IF: {if_freq * 1e-6:.3f} MHz")

    def set_octave_output(self, el: str, mode: RFOutputMode):
        self._require_qm()
        self._check_el(el)
        self.qm.octave.set_rf_output_mode(el, mode)
        _logger.info(f"set output for element {el} to {mode}")

    def set_octave_gain(self, el: str, gain: float):
        self._require_qm()
        self._check_el(el)
        self.qm.octave.set_rf_output_gain(el, gain)
        self.elements[el]["gain"] = gain
        _logger.info(f"set gain for element {el} to {gain} dB")

    def get_octave_gain(self, el: str) -> float:
        self._require_qm()
        self._check_el(el)
        return self.elements[el]["gain"]

    def get_element_lo(self, el: Union[str, Iterable[str]]) -> Union[float, list[float]]:
        if isinstance(el, (list, tuple)):
            for e in el:
                self._check_el(e)
            return [self.elements[e]["LO"] for e in el]
        else:
            self._check_el(el)
            return self.elements[el]["LO"]

    def get_element_if(self, el: Union[str, Iterable[str]]) -> Union[float, list[float]]:
        if isinstance(el, (list, tuple)):
            for e in el:
                self._check_el(e)
            return [self.elements[e]["IF"] for e in el]
        else:
            self._check_el(el)
            return self.elements[el]["IF"]

    def calculate_el_if_fq(
        self,
        el: str,
        freq: Union[float, Iterable[float], np.ndarray],
        lo_freq: Optional[float] = None,
        *,
        max_if_hz: float = 500e6,
        as_int: bool = False,
        round_mode: str = "round",
    ):
        self._check_el(el)

        lo = self.elements[el]["LO"] if lo_freq is None else lo_freq
        if lo is None:
            raise QMConfigError(f"Element '{el}' LO is undefined.")

        was_scalar = np.isscalar(freq)
        f_arr = np.asarray(freq, dtype=float)
        if f_arr.ndim == 0:
            f_arr = f_arr.reshape(1)

        if_arr = f_arr - float(lo)

        too_big = np.abs(if_arr) > float(max_if_hz)
        if np.any(too_big):
            bad_vals = if_arr[too_big] / 1e6
            preview = ", ".join(f"{v:.1f}" for v in bad_vals[:5])
            more = "" if bad_vals.size <= 5 else f" (+{bad_vals.size - 5} more)"
            raise ValueError(
                f"One or more IFs exceed ±{max_if_hz / 1e6:.0f} MHz for '{el}'. "
                f"Offending IF MHz: {preview}{more}."
            )

        if as_int:
            if round_mode == "round":
                if_arr = np.rint(if_arr).astype(int)
            elif round_mode == "floor":
                if_arr = np.floor(if_arr).astype(int)
            elif round_mode == "ceil":
                if_arr = np.ceil(if_arr).astype(int)
            else:
                raise ValueError("round_mode must be 'round', 'floor', or 'ceil'.")

        if was_scalar:
            return if_arr.item()
        return if_arr

    def calibration_el_octave(
        self,
        el: Optional[Union[str, Iterable[str]]] = None,
        target_LO: Optional[Union[float, Iterable[float]]] = None,
        target_IF: Optional[Union[float, Iterable[float]]] = None,
        save_to_db: bool = True,
        output_mode: RFOutputMode = RFOutputMode.on,
    ):
        """
        Calibrate Octave for one or more elements.

        Parameters
        ----------
        el : str | iterable[str] | None
            - None: calibrate all elements in self.elements
            - str: single element name
            - iterable[str]: list/tuple of element names
        target_LO : float | iterable[float] | None
            - If None, uses get_element_lo(e) per element.
            - If float, broadcast to all elements.
            - If iterable, must match len(el).
        target_IF : float | iterable[float] | None
            - Same rules as target_LO.
        """
        self._require_qm()

        # --- helper for a single element ----------------------------------------
        def _calibrate_one(e: str, lo_val: Optional[float], if_val: Optional[float]) -> None:
            #if self._is_external_lo(e):
            #    _logger.info(f"Skipping octave calibration for '{e}' (external LO source).")
            #    return

            # Fill in LO/IF from element config if not provided
            if lo_val is None:
                lo_val = float(self.get_element_lo(e))
            if if_val is None:
                if_val = float(self.get_element_if(e))

            _logger.info(f"calibrating: {e} with LO, IF = {lo_val}, {if_val}")
            self.qm.calibrate_element(e, {lo_val: (if_val,)}, save_to_db=save_to_db)
            self.set_octave_output(e, output_mode)

        # --- case 1: el is None → all elements ----------------------------------
        if el is None:
            _logger.info("No element specified, calibrating all elements")
            for e, cfg in self.elements.items():
                # Use stored LO/IF if present; fallback to getters if needed
                lo_val = cfg.get("LO")
                if_val = cfg.get("IF")
                _calibrate_one(e, lo_val, if_val)
            return

        # --- normalize el to a list ---------------------------------------------
        if isinstance(el, str):
            elements = [el]
        else:
            elements = list(el)

        n = len(elements)
        if n == 0:
            _logger.warning("Empty element list passed to calibration_el_octave; nothing to do.")
            return

        # --- normalize LO list ---------------------------------------------------
        if isinstance(target_LO, (list, tuple)):
            if len(target_LO) != n:
                raise ValueError(
                    f"target_LO has length {len(target_LO)} but el has length {n}"
                )
            lo_list = list(target_LO)
        else:
            # scalar or None → broadcast
            lo_list = [target_LO] * n

        # --- normalize IF list ---------------------------------------------------
        if isinstance(target_IF, (list, tuple)):
            if len(target_IF) != n:
                raise ValueError(
                    f"target_IF has length {len(target_IF)} but el has length {n}"
                )
            if_list = list(target_IF)
        else:
            if_list = [target_IF] * n

        # --- loop over all requested elements ------------------------------------
        for e, lo_val, if_val in zip(elements, lo_list, if_list):
            _calibrate_one(e, lo_val, if_val)

    # ───────────────────────── execution / simulation ──────────────────────────
    @contextlib.contextmanager
    def _pump_on(self):
        try:
            if self.spa_pump_sc:
                self.spa_pump_sc.do_set_output_status(True)
            yield
        finally:
            if self.spa_pump_sc:
                with contextlib.suppress(Exception):
                    self.spa_pump_sc.do_set_output_status(False)

    def serialize_program(
        self,
        qua_prog=None,
        path: Path | str = "",
        filename: str = "debug.py",
        *,
        use_last_snapshot: bool = True,
    ) -> str:
        """
        Serialize a QUA program to a Python script using QM's generate_qua_script.

        If qua_prog is None, uses the most recently remembered program.
        If use_last_snapshot=True and we're serializing the most recent program,
        uses the config snapshot captured at submission/run time (more accurate
        than current qm_config if you later burned changes).
        """
        with self._lock:
            if qua_prog is None:
                qua_prog = self.current_program

            _require(qua_prog is not None, "No program has been run/queued/simulated yet; pass qua_prog explicitly.", QMJobError)

            # Prefer the snapshot if serializing the most recent program
            if use_last_snapshot and (qua_prog is self.current_program) and (self._last_program_cfg is not None):
                cfg = deepcopy(self._last_program_cfg)
            else:
                cfg = self.qm_config or self.build_qm_config()

        full_path = Path(path) / filename
        full_path.parent.mkdir(parents=True, exist_ok=True)

        with open(full_path, "w") as f:
            print(generate_qua_script(qua_prog, cfg), file=f)

        return str(full_path)

    def set_exec_mode(self, mode: ExecMode | str) -> None:
        self.exec_mode = _coerce_exec_mode(mode)
        _logger.info(f"QuaProgramManager exec_mode set to: {self.exec_mode}")

    def get_exec_mode(self) -> ExecMode:
        return self.exec_mode

    @staticmethod
    def _program_exec_mode(qua_prog) -> ExecMode | None:
        """
        Optional per-program declaration.

        Supported conventions:
        - qua_prog._exec_mode = ExecMode.SIMULATE / "simulate" / "hardware"
        - qua_prog._simulate_only = True  (shorthand for simulate)
        """
        if getattr(qua_prog, "_simulate_only", False):
            return ExecMode.SIMULATE

        m = getattr(qua_prog, "_exec_mode", None)
        if m is None:
            return None

        try:
            return _coerce_exec_mode(m)
        except Exception:
            # if user puts garbage there, fail loudly
            raise QMConfigError(f"Invalid qua_prog._exec_mode = {m!r}")

    def run_program(
        self,
        qua_prog,
        n_total: int,
        print_report: bool = True,
        show_progress: bool = True,
        processors: list | None = None,
        progress_handle: str = "iteration",
        auto_job_halt: bool = True,
        process_in_sim: bool | None = None,
        *,
        use_queue: bool = False,
        queue_to_start: bool = False,
        queue_only: bool = False,
        **kwargs,
    ) -> RunResult:
        """
        Hardware-only execution.

        Supports optional multi-user queue submission:
        - use_queue=True: submit to QM queue
        - queue_to_start=True: submit to front
        - queue_only=True: submit and return immediately (no wait / no fetch)

        Also records the most recent program + config snapshot for serialize_program().
        """
        # 1) manager-wide guard
        if self.exec_mode == ExecMode.SIMULATE:
            raise QMJobError(
                "run_program() is hardware-only, but QuaProgramManager is in ExecMode.SIMULATE. "
                "Call manager.set_exec_mode('hardware') or use manager.simulate(...)."
            )

        # 2) program-level guard
        p_mode = self._program_exec_mode(qua_prog)
        if p_mode == ExecMode.SIMULATE:
            raise QMJobError(
                "This QUA program is marked as SIMULATE-only. "
                "Use manager.simulate(qua_prog, ...) instead of run_program()."
            )

        self._require_qm()

        # Snapshot config NOW (so serialize_program matches what we submitted/ran,
        # even if you burn a new config later)
        cfg_snapshot = self.qm_config or self.build_qm_config()

        # Remember most recent program (works even for queue_only)
        if hasattr(self, "_remember_program"):
            self._remember_program(
                qua_prog,
                cfg=cfg_snapshot,
                meta={"last_mode": "hardware", "use_queue": bool(use_queue)},
            )
        else:
            # backward-compat if you didn't add _remember_program yet
            self.current_program = qua_prog

        out = Output()
        sim_samples = None  # always None in hardware path

        pending = None
        try:
            with self._pump_on():
                # ---- start job (queue or immediate) ----
                try:
                    if use_queue:
                        pending = (
                            self.qm.queue.add_to_start(qua_prog)
                            if queue_to_start
                            else self.qm.queue.add(qua_prog)
                        )

                        if queue_only:
                            meta = {
                                "n_total": int(n_total),
                                "queued": True,
                                "queue_only": True,
                                "pending_job": pending,
                                "job_id": getattr(pending, "job_id", None),
                                "time_added": getattr(pending, "time_added", None),
                                "user_added": getattr(pending, "user_added", None),
                            }
                            if hasattr(self, "_remember_program"):
                                self._remember_program(qua_prog, cfg=cfg_snapshot, meta=meta)

                            return RunResult(
                                mode=ExecMode.HARDWARE,
                                output=Output(),
                                sim_samples=None,
                                metadata=meta,
                            )

                        # Wait until it actually starts executing
                        self.job = pending.wait_for_execution()
                    else:
                        self.job = self.qm.execute(qua_prog)

                except StreamTerminatedError as e:
                    raise QMConnectionError("Connection lost during execute/queue.") from e
                except Exception as e:
                    raise QMJobError(f"Failed to start job: {e}") from e

                # ---- progress ----
                if show_progress:
                    self._report_progress(self.job, n_total, progress_handle)

                # ---- execution report ----
                if print_report:
                    with contextlib.suppress(Exception):
                        report = self.job.execution_report()
                        if report:
                            _logger.info("Execution report:\n%s", report)

                # ---- fetch results ----
                for name, handle in list(self.job.result_handles.items()):
                    try:
                        out[name] = handle.fetch_all()
                    except Exception as e:
                        _logger.error(f"Fetch failed for handle '{name}': {e}")

        finally:
            if auto_job_halt:
                with contextlib.suppress(Exception):
                    self.halt_job()

        # ---- processing ----
        procs = processors or self.processors

        if process_in_sim is None:
            process_in_sim = bool(_prog_flag(qua_prog, "_process_in_sim", False))

        # hardware-only: process if processors exist (ignore process_in_sim here)
        if procs:
            for proc in procs:
                try:
                    out = proc(out, **kwargs)
                except Exception as e:
                    pname = getattr(proc, "__name__", repr(proc))
                    _logger.error(f"Processor {pname} failed: {e}")

        meta = {"n_total": int(n_total)}
        if use_queue:
            meta.update(
                {
                    "queued": True,
                    "queue_only": False,
                    "job_id": getattr(pending, "job_id", None) if pending is not None else None,
                    "time_added": getattr(pending, "time_added", None) if pending is not None else None,
                    "user_added": getattr(pending, "user_added", None) if pending is not None else None,
                }
            )

        return RunResult(mode=ExecMode.HARDWARE, output=out, sim_samples=sim_samples, metadata=meta)



    def halt_job(self):
        if not self.job:
            return
        try:
            self.job.halt()
            _logger.info("Job Halted Successfully")
        except StreamTerminatedError:
            _logger.warning("Idle too long! Connection lost")
        except Exception as e:
            _logger.error(f"attempting to halt job failed: {e}")

    def _report_progress(self, job: RunningQmJob, n_total: int, handle: str):
        if not n_total:
            _logger.info("n_total not passed, will not report progress...")
            return

        handles = job.result_handles
        if handle not in handles.keys():
            _logger.warning("Progress handle not found; will not report progress.")
            while handles.is_processing():
                time.sleep(0.05)
            return

        show_bar = _logger.isEnabledFor(logging.INFO)
        with tqdm(total=n_total, desc="Running Program...", disable=not show_bar) as bar:
            while handles.is_processing():
                time.sleep(0.05)
                with contextlib.suppress(Exception):
                    h = handles.get(handle)
                    if h:
                        bar.n = h.fetch_all()
                        bar.refresh()

            with contextlib.suppress(Exception):
                h = handles.get(handle)
                if h:
                    bar.n = h.fetch_all()
                    bar.refresh()

    # -------------------- plotting helpers --------------------
    def _plot_sim_custom(
        self,
        sim,
        *,
        plot_params: Dict[str, Any],
        controllers=("con1",),
        t_begin: float | None = None,
        t_end: float | None = None,
    ):
        pp = plot_params or {}
        which = pp.get("which", "both")
        channels = pp.get("channels", None)
        time_unit = str(pp.get("time_unit", "ns"))
        xlim = pp.get("xlim", None)
        ylim = pp.get("ylim", None)
        dylim = pp.get("digital_ylim", None)
        title = pp.get("title", None)
        grid = bool(pp.get("grid", True))
        legend = bool(pp.get("legend", True))

        unit_scale = {"ns": 1.0, "us": 1e-3, "ms": 1e-6}.get(time_unit, 1.0)

        def t_axis(n: int, fs_hz: float):
            return (np.arange(n) / float(fs_hz)) * 1e9 * unit_scale

        if t_begin is not None or t_end is not None:
            tb = 0.0 if t_begin is None else float(t_begin)
            te = float("inf") if t_end is None else float(t_end)
            if tb < 0:
                raise ValueError("t_begin must be ≥ 0 in the chosen time_unit.")
            if not np.isinf(te) and te <= tb:
                raise ValueError("t_end must be greater than t_begin.")
        else:
            tb = te = None

        include_analog = which in ("analog", "both")
        include_digital = which in ("digital", "both")

        fig = plt.figure(constrained_layout=True, figsize=(8.5, 4.2))
        gs = GridSpec(nrows=1, ncols=2, figure=fig, width_ratios=[1.0, 0.45], wspace=0.06)
        ax = fig.add_subplot(gs[0, 0])
        ax2 = None
        ax_leg = fig.add_subplot(gs[0, 1])
        ax_leg.set_axis_off()

        analog_plotted = digital_plotted = False

        for ctrl in controllers:
            if ctrl not in sim:
                continue
            con = sim[ctrl]

            if include_analog:
                for name, y in con.analog.items():
                    if channels and name not in channels:
                        continue
                    if len(y) == 0 or not np.any(y):
                        continue
                    fs = con.analog_sampling_rate.get(name, 1e9)
                    t = t_axis(len(y), fs)
                    y_arr = np.asarray(y)

                    if tb is not None:
                        mask = (t >= tb) & (t <= te)
                        if not np.any(mask):
                            continue
                        t = t[mask]
                        y_arr = y_arr[mask]

                    ax.plot(t, y_arr, label=f"{ctrl}:{name}")
                    analog_plotted = True

            if include_digital:
                for name, d in con.digital.items():
                    if channels and name not in channels:
                        continue
                    if len(d) == 0 or not np.any(d):
                        continue
                    if ax2 is None:
                        ax2 = ax.twinx()

                    fs_dig = 1e9
                    t = t_axis(len(d), fs_dig)
                    d_arr = np.asarray(d, dtype=float)

                    if tb is not None:
                        mask = (t >= tb) & (t <= te)
                        if not np.any(mask):
                            continue
                        t = t[mask]
                        d_arr = d_arr[mask]

                    ax2.step(t, d_arr, where="post", linestyle="--", label=f"{ctrl}:{name} (D)")
                    digital_plotted = True

        ax.set_xlabel(f"Time [{time_unit}]")
        if analog_plotted:
            ax.set_ylabel("Voltage [V]")
        if digital_plotted and ax2 is not None:
            ax2.set_ylabel("Digital")
            ax2.set_ylim(*(dylim if dylim else (-0.1, 1.1)))

        if title:
            ax.set_title(title)
        if grid:
            ax.grid(True, which="both", axis="both", alpha=0.3)

        if xlim:
            ax.set_xlim(*xlim)
            if ax2 is not None:
                ax2.set_xlim(*xlim)
        elif tb is not None:
            x_min = tb
            x_max = te
            if np.isinf(x_max):
                cur_xlim = ax.get_xlim()
                x_max = cur_xlim[1]
            ax.set_xlim(x_min, x_max)
            if ax2 is not None:
                ax2.set_xlim(x_min, x_max)

        if ylim and analog_plotted:
            ax.set_ylim(*ylim)

        if legend:
            h1, l1 = ax.get_legend_handles_labels()
            h2, l2 = (ax2.get_legend_handles_labels() if ax2 is not None else ([], []))
            handles = h1 + h2
            labels = l1 + l2
            if handles:
                ax_leg.legend(handles, labels, loc="center left", frameon=False)

        plt.show()

    # -------------------- NEW simulate API (no set_simulate_params) --------------------
    def simulate(
        self,
        program,
        *,
        duration: int = 4000,
        plot: bool = True,
        plot_params: Optional[Dict[str, Any]] = None,
        controllers=("con1",),
        t_begin: float | None = None,
        t_end: float | None = None,
        compiler_options=None,
    ):
        """
        Simulate a QUA program.

        All simulation parameters are passed here (no global set_simulate_params()).

        Parameters
        ----------
        duration:
            Total simulation duration in ns (your previous convention).
            Note: We keep your legacy factor-of-4 behavior: SimulationConfig(duration=int(duration/4)).
        plot:
            If True, plot simulated samples.
        plot_params:
            Dict overriding defaults in _DEFAULT_PLOT_PARAMS.
        controllers, t_begin, t_end:
            Forwarded to _plot_sim_custom().
        """
        cfg = self.qm_config or self.build_qm_config()
        _require(cfg, "No config available for simulation.")

        # Merge plot params with defaults
        pp = deepcopy(_DEFAULT_PLOT_PARAMS)
        if plot_params:
            pp.update(plot_params)

        # keep your factor-of-4 behavior
        sim_config = SimulationConfig(duration=int(int(duration) / 4))
        job = self._qmm.simulate(cfg, program, sim_config, compiler_options=compiler_options)
        sim_raw = job.get_simulated_samples()
        sim_labeled = self._relabel_simulator_samples(sim_raw)

        if plot:
            self._plot_sim_custom(
                sim_labeled,
                plot_params=pp,
                controllers=controllers,
                t_begin=t_begin,
                t_end=t_end,
            )

        return sim_labeled

    def get_simulation_results(self):
        return self.simulate_config.simulation_samples

    def run_continuous_wave(self, elements: list, el_freqs: list, pulses:list,  gain=1.0):
        self._require_qm()
        _require(len(elements) == len(el_freqs), "elements and frequencies number don't match up!")
        for el, if_freq in zip(elements, el_freqs):
            self._check_el(el)
            self.qm.set_intermediate_frequency(el, if_freq)
        with qua.program() as continuous_wave:
            with qua.infinite_loop_():
                for el, pulse in zip(elements, pulses):
                    qua.play(pulse * qua.amp(gain), el)
        self.run_program(continuous_wave, n_total=1, print_report=False, show_progress=False, auto_job_halt=False)

    def close_OPX_System(self):
        for element in list(self.elements.keys()):
            with contextlib.suppress(Exception):
                self.set_octave_output(element, RFOutputMode.off)
        self._qmm.close_all_qms()
        self.qm = None
        _logger.info("All QMs closed; manager reset.")

    # ───────────────────────── Convenience persisted HW setters ─────────────────
    def hw_set_octave_rf_output(
        self,
        *,
        octave: str,
        rf_out: int,
        lo_frequency: float | None = None,
        lo_source: str | None = None,
        output_mode: str | None = None,
        gain: float | None = None,
        autosave: bool = True,
        autoburn: bool = True,
        fill_missing_lo_from_current: bool = True,
    ):
        def _patch(hw: dict, extras: dict):
            octaves = hw.setdefault("octaves", {})
            octd = octaves.setdefault(octave, {})
            rf_outs = octd.setdefault("RF_outputs", {})

            k = _key_like(rf_outs, rf_out)
            if k not in rf_outs:
                rf_outs[k] = {}

            ch = rf_outs[k]
            if not isinstance(ch, dict):
                raise QMConfigError(f"octaves[{octave}].RF_outputs[{rf_out}] is not a dict")

            if lo_frequency is not None:
                ch["LO_frequency"] = float(lo_frequency)
            if lo_source is not None:
                ch["LO_source"] = str(lo_source)
            if output_mode is not None:
                ch["output_mode"] = str(output_mode)
            if gain is not None:
                ch["gain"] = float(gain)

            if "LO_frequency" not in ch:
                if fill_missing_lo_from_current:
                    cur = self.qm_config or self.build_qm_config()
                    cur_rf = _get_nested(cur, ["octaves", octave, "RF_outputs"], {})
                    if isinstance(cur_rf, dict):
                        kk = _key_like(cur_rf, rf_out)
                        cur_ch = cur_rf.get(kk)
                        if isinstance(cur_ch, dict) and "LO_frequency" in cur_ch:
                            ch["LO_frequency"] = float(cur_ch["LO_frequency"])

                if "LO_frequency" not in ch:
                    raise QMConfigError(
                        f"Missing LO_frequency for octaves[{octave}].RF_outputs[{rf_out}]. "
                        f"Pass lo_frequency=... or ensure hardware.json has it."
                    )

        self.patch_hardware(_patch, autosave=autosave, autoburn=autoburn)

    def hw_set_element_time_of_flight(
        self,
        *,
        element: str,
        time_of_flight: int,
        autosave: bool = True,
        autoburn: bool = True,
        allow_while_running: bool = False,
    ):
        """
        Persistently update elements[element].time_of_flight in hardware_base
        and optionally burn + save.
        """
        def _patch(hw: dict, extras: dict):
            elems = hw.setdefault("elements", {})
            _require(element in elems, f"Unknown element '{element}' in hardware.", QMConfigError)

            el = elems[element]
            if not isinstance(el, dict):
                raise QMConfigError(f"elements['{element}'] is not a dict")

            el["time_of_flight"] = int(time_of_flight)

        self.patch_hardware(_patch, autosave=autosave, autoburn=autoburn, allow_while_running=allow_while_running)

    def hw_set_element_intermediate_frequency(
        self,
        *,
        element: str,
        intermediate_frequency: float,
        autosave: bool = True,
        autoburn: bool = True,
        apply_live_if_possible: bool = True,
        allow_while_running: bool = False,
    ):
        """
        Persistently update elements[element].intermediate_frequency and optionally burn+save.

        If apply_live_if_possible=True and a QM is open, also call qm.set_intermediate_frequency
        to reflect the change immediately (without waiting for burn).
        """
        if_hz = float(intermediate_frequency)

        def _patch(hw: dict, extras: dict):
            elems = hw.setdefault("elements", {})
            _require(element in elems, f"Unknown element '{element}' in hardware.", QMConfigError)

            el = elems[element]
            if not isinstance(el, dict):
                raise QMConfigError(f"elements['{element}'] is not a dict")

            el["intermediate_frequency"] = if_hz

        # patch + optionally burn/save
        self.patch_hardware(_patch, autosave=autosave, autoburn=autoburn, allow_while_running=allow_while_running)

        # optional: apply to live QM immediately (useful if autoburn=False)
        if apply_live_if_possible and (self.qm is not None) and (not autoburn):
            with contextlib.suppress(Exception):
                self.qm.set_intermediate_frequency(element, if_hz)
                if element in self.elements:
                    self.elements[element]["IF"] = if_hz
                _logger.info(f"Live IF updated for {element}: {if_hz/1e6:.3f} MHz")

    # ───────────────────────── Controller IO offset setters ─────────────────────────
    def hw_set_controller_analog_output_offset(
        self,
        *,
        controller: str,
        port: int,
        offset: float,
        autosave: bool = True,
        autoburn: bool = True,
        allow_while_running: bool = False,
        create_if_missing: bool = True,
    ) -> None:
        """
        Persistently set controllers[controller].analog_outputs[port].offset.

        Notes
        -----
        - This updates hardware_base (hardware.json layer) and optionally burns/saves.
        - Keys may be int or str in JSON; we preserve existing style via _key_like.
        """
        def _patch(hw: dict, extras: dict) -> None:
            ctrls = hw.setdefault("controllers", {})
            _require(controller in ctrls, f"Unknown controller '{controller}' in hardware.", QMConfigError)

            cdict = ctrls[controller]
            _require(isinstance(cdict, dict), f"controllers['{controller}'] is not a dict", QMConfigError)

            aouts = cdict.setdefault("analog_outputs", {})
            _require(isinstance(aouts, dict), f"controllers['{controller}'].analog_outputs is not a dict", QMConfigError)

            k = _key_like(aouts, port)
            if k not in aouts:
                if not create_if_missing:
                    raise QMConfigError(
                        f"controllers['{controller}'].analog_outputs has no port {port}. "
                        f"Set create_if_missing=True to create it."
                    )
                aouts[k] = {}

            ch = aouts[k]
            _require(isinstance(ch, dict), f"analog_outputs[{port}] is not a dict", QMConfigError)
            ch["offset"] = float(offset)

        self.patch_hardware(_patch, autosave=autosave, autoburn=autoburn, allow_while_running=allow_while_running)

    def hw_set_controller_analog_input_offset(
        self,
        *,
        controller: str,
        port: int,
        offset: float,
        autosave: bool = True,
        autoburn: bool = True,
        allow_while_running: bool = False,
        create_if_missing: bool = True,
    ) -> None:
        """
        Persistently set controllers[controller].analog_inputs[port].offset.
        """
        def _patch(hw: dict, extras: dict) -> None:
            ctrls = hw.setdefault("controllers", {})
            _require(controller in ctrls, f"Unknown controller '{controller}' in hardware.", QMConfigError)

            cdict = ctrls[controller]
            _require(isinstance(cdict, dict), f"controllers['{controller}'] is not a dict", QMConfigError)

            ains = cdict.setdefault("analog_inputs", {})
            _require(isinstance(ains, dict), f"controllers['{controller}'].analog_inputs is not a dict", QMConfigError)

            k = _key_like(ains, port)
            if k not in ains:
                if not create_if_missing:
                    raise QMConfigError(
                        f"controllers['{controller}'].analog_inputs has no port {port}. "
                        f"Set create_if_missing=True to create it."
                    )
                ains[k] = {}

            ch = ains[k]
            _require(isinstance(ch, dict), f"analog_inputs[{port}] is not a dict", QMConfigError)
            ch["offset"] = float(offset)

        self.patch_hardware(_patch, autosave=autosave, autoburn=autoburn, allow_while_running=allow_while_running)

    def hw_set_controller_io_offsets(
        self,
        *,
        controller: str,
        analog_outputs: dict[int, float] | None = None,
        analog_inputs: dict[int, float] | None = None,
        autosave: bool = True,
        autoburn: bool = True,
        allow_while_running: bool = False,
        create_if_missing: bool = True,
    ) -> None:
        """
        Bulk setter for controller analog IO offsets.

        Example
        -------
        hw_set_controller_io_offsets(
            controller="con1",
            analog_outputs={1: 0.0, 2: 0.0, 5: -0.002},
            analog_inputs={1: 0.00947713, 2: 0.00962465},
        )
        """
        ao_map = dict(analog_outputs or {})
        ai_map = dict(analog_inputs or {})

        def _patch(hw: dict, extras: dict) -> None:
            ctrls = hw.setdefault("controllers", {})
            _require(controller in ctrls, f"Unknown controller '{controller}' in hardware.", QMConfigError)
            cdict = ctrls[controller]
            _require(isinstance(cdict, dict), f"controllers['{controller}'] is not a dict", QMConfigError)

            if ao_map:
                aouts = cdict.setdefault("analog_outputs", {})
                _require(isinstance(aouts, dict), f"controllers['{controller}'].analog_outputs is not a dict", QMConfigError)
                for p, off in ao_map.items():
                    k = _key_like(aouts, int(p))
                    if k not in aouts:
                        if not create_if_missing:
                            raise QMConfigError(
                                f"controllers['{controller}'].analog_outputs has no port {p}."
                            )
                        aouts[k] = {}
                    ch = aouts[k]
                    _require(isinstance(ch, dict), f"analog_outputs[{p}] is not a dict", QMConfigError)
                    ch["offset"] = float(off)

            if ai_map:
                ains = cdict.setdefault("analog_inputs", {})
                _require(isinstance(ains, dict), f"controllers['{controller}'].analog_inputs is not a dict", QMConfigError)
                for p, off in ai_map.items():
                    k = _key_like(ains, int(p))
                    if k not in ains:
                        if not create_if_missing:
                            raise QMConfigError(
                                f"controllers['{controller}'].analog_inputs has no port {p}."
                            )
                        ains[k] = {}
                    ch = ains[k]
                    _require(isinstance(ch, dict), f"analog_inputs[{p}] is not a dict", QMConfigError)
                    ch["offset"] = float(off)

        self.patch_hardware(_patch, autosave=autosave, autoburn=autoburn, allow_while_running=allow_while_running)


    # ───────────────────────── Queue + Multi-user helpers ─────────────────────────
    def list_open_qms(self) -> list[str]:
        return list(self._qmm.list_open_quantum_machines())

    def attach_to_open_qm(self, qm_id: str | None = None, *, init_elements: bool = True) -> str:
        qms = self.list_open_qms()
        _require(len(qms) > 0, "No open QMs found on the QOP.", QMConnectionError)
        if qm_id is None:
            qm_id = qms[0]
        _require(qm_id in qms, f"QM id '{qm_id}' not in list_open_qms(): {qms}", QMConnectionError)

        with self._lock:
            self.qm = self._qmm.get_qm(qm_id)
            self.job = None
            if init_elements:
                self.elements = self._init_elements()
        _logger.info(f"Attached to existing QM: {qm_id}")
        return qm_id

    def queue_count(self) -> int:
        self._require_qm()
        return int(self.qm.queue.count)

    def queue_pending_jobs(self) -> list:
        self._require_qm()
        return list(self.qm.queue.pending_jobs)

    def queue_get_at(self, position: int):
        self._require_qm()
        _require(position >= 1, "Queue is 1-based: position must be >= 1", QMJobError)
        return self.qm.queue.get_at(int(position))

    def queue_get(self, job_id: str):
        self._require_qm()
        return self.qm.queue.get(job_id)

    def queue_get_by_user_id(self, user_id: str):
        self._require_qm()
        return self.qm.queue.get_by_user_id(user_id)

    def queue_remove_by_id(self, job_id: str) -> None:
        self._require_qm()
        self.qm.queue.remove_by_id(job_id)

    def queue_remove_by_position(self, position: int) -> None:
        self._require_qm()
        _require(position >= 1, "Queue is 1-based: position must be >= 1", QMJobError)
        self.qm.queue.remove_by_position(int(position))

    def queue_remove_by_user_id(self, user_id: str) -> None:
        self._require_qm()
        self.qm.queue.remove_by_user_id(user_id)

    # ───────────────────────── logging control ─────────────────────────
    @contextlib.contextmanager
    def quiet_external_logs(
        self,
        *,
        qm_level: int = logging.WARNING,
        extra_loggers: Optional[Iterable[str]] = None,
    ):
        """
        Temporarily suppress noisy INFO logs from external libs (QM compilation spam, etc.).
        """
        names = ["qm"]
        if extra_loggers:
            names.extend(list(extra_loggers))

        old = []
        for name in names:
            lg = logging.getLogger(name)
            old.append((lg, lg.level))
            lg.setLevel(qm_level)
        try:
            yield
        finally:
            for lg, lvl in old:
                lg.setLevel(lvl)

    # ───────────────────────── queue submit wrappers ─────────────────────────
    def queue_submit(self, qua_prog, *, to_start: bool = False, quiet: bool = True):
        """
        Submit program to QM queue and return QmPendingJob.

        IMPORTANT:
        - Remembers this program + a config snapshot so serialize_program() works after
        queue-based workflows (e.g. your RB batching).
        """
        self._require_qm()

        # Snapshot config at submit-time so debug serialization matches what was submitted
        cfg_snapshot = self.qm_config or self.build_qm_config()

        # Remember program even if user never calls run_program()
        if hasattr(self, "_remember_program"):
            self._remember_program(
                qua_prog,
                cfg=cfg_snapshot,
                meta={
                    "last_mode": "hardware",
                    "queued": True,
                    "queue_submit": True,
                    "queue_to_start": bool(to_start),
                },
            )
        else:
            self.current_program = qua_prog

        cm = self.quiet_external_logs() if quiet else contextlib.nullcontext()
        with cm:
            with self._lock:
                try:
                    pending = self.qm.queue.add_to_start(qua_prog) if to_start else self.qm.queue.add(qua_prog)
                except StreamTerminatedError as e:
                    raise QMConnectionError("Connection lost while adding job to queue.") from e
                except Exception as e:
                    raise QMJobError(f"Failed to add job to queue: {e}") from e

        # Update remembered metadata with pending job info (best effort)
        if hasattr(self, "_remember_program"):
            self._remember_program(
                qua_prog,
                cfg=cfg_snapshot,
                meta={
                    "job_id": getattr(pending, "job_id", None),
                    "time_added": getattr(pending, "time_added", None),
                    "user_added": getattr(pending, "user_added", None),
                },
            )

        return pending

    def queue_submit_many(self, programs, *, to_start: bool = False, quiet: bool = True):
        """
        Submit many programs. The last submitted becomes current_program (serializable).
        """
        pendings = []
        for p in programs:
            pendings.append(self.queue_submit(p, to_start=to_start, quiet=quiet))
        return pendings

    # ───────────────────────── progress helpers ─────────────────────────
    @staticmethod
    def _progress_value(x) -> int:
        if x is None:
            return 0
        if isinstance(x, (int, np.integer)):
            return int(x)
        if isinstance(x, (float, np.floating)):
            return int(x)
        if isinstance(x, (list, tuple)) and len(x) > 0:
            return int(x[-1])
        if isinstance(x, np.ndarray):
            if x.size == 0:
                return 0
            return int(x.reshape(-1)[-1])
        try:
            return int(x)
        except Exception:
            return 0

    def _collect_output_from_job(self, job, *, print_report: bool):
        out = Output()
        if print_report:
            with contextlib.suppress(Exception):
                report = job.execution_report()
                if report:
                    _logger.info("Execution report:\n%s", report)
        for name, handle in list(job.result_handles.items()):
            try:
                out[name] = handle.fetch_all()
            except Exception as e:
                _logger.error(f"Fetch failed for handle '{name}': {e}")
        return out

    # ───────────────────────── run many queued jobs with ONE global bar ─────────────────────────
    def queue_run_many(
        self,
        pending_jobs: list,
        *,
        n_totals: int | list[int],
        processors: list | None = None,
        progress_handle: str = "iteration",
        show_total_progress: bool = True,
        print_report: bool = False,
        auto_job_halt: bool = True,
        quiet: bool = True,
        desc: str = "Running queued...",
        sleep_s: float = 0.05,
        **proc_kwargs,
    ) -> list["RunResult"]:
        """
        Run queued jobs sequentially, showing ONE global tqdm progress bar.

        Note: "most recent program for serialize_program()" is handled at submit-time
        in queue_submit(), since we don't reliably recover the QUA object from a pending/job.
        """
        self._require_qm()

        if isinstance(n_totals, int):
            n_list = [int(n_totals)] * len(pending_jobs)
        else:
            n_list = [int(x) for x in n_totals]
            _require(len(n_list) == len(pending_jobs), "n_totals length must match pending_jobs length.", QMJobError)

        total_iters = int(sum(n_list))
        procs = processors or self.processors

        show_bar = bool(show_total_progress) and _logger.isEnabledFor(logging.INFO)
        cm = self.quiet_external_logs() if quiet else contextlib.nullcontext()

        results: list[RunResult] = []
        offset = 0

        with cm, tqdm(total=total_iters, desc=desc, disable=not show_bar, leave=True) as bar:
            for pending, n_total in zip(pending_jobs, n_list):
                try:
                    job = pending.wait_for_execution()
                except StreamTerminatedError as e:
                    raise QMConnectionError("Connection lost while waiting for queued job execution.") from e
                except Exception as e:
                    raise QMJobError(f"Queued job failed to start: {e}") from e

                handles = job.result_handles
                last = 0

                if progress_handle in handles.keys():
                    while handles.is_processing():
                        time.sleep(float(sleep_s))
                        with contextlib.suppress(Exception):
                            h = handles.get(progress_handle)
                            if h is not None:
                                cur = self._progress_value(h.fetch_all())
                                cur = max(0, min(int(cur), int(n_total)))
                                if cur != last:
                                    last = cur
                                    bar.n = offset + last
                                    bar.refresh()

                    with contextlib.suppress(Exception):
                        h = handles.get(progress_handle)
                        if h is not None:
                            cur = self._progress_value(h.fetch_all())
                            cur = max(0, min(int(cur), int(n_total)))
                            last = cur
                            bar.n = offset + last
                            bar.refresh()
                else:
                    while handles.is_processing():
                        time.sleep(float(sleep_s))

                try:
                    out = self._collect_output_from_job(job, print_report=print_report)
                finally:
                    if auto_job_halt:
                        with contextlib.suppress(Exception):
                            job.halt()

                if procs:
                    for proc in procs:
                        try:
                            out = proc(out, **proc_kwargs)
                        except Exception as e:
                            pname = getattr(proc, "__name__", repr(proc))
                            _logger.error(f"Processor {pname} failed: {e}")

                bar.n = offset + int(n_total)
                bar.refresh()

                results.append(
                    RunResult(
                        mode=ExecMode.HARDWARE,
                        output=out,
                        sim_samples=None,
                        metadata={"n_total": int(n_total), "queued": True},
                    )
                )
                offset += int(n_total)

            bar.n = total_iters
            bar.refresh()

        return results

    # ───────────────────────── submit-many with progress bar ─────────────────────────
    def queue_submit_many_with_progress(
        self,
        programs,
        *,
        to_start: bool = False,
        quiet: bool = True,
        show_submit_progress: bool = True,
        desc: str = "Submitting to queue...",
    ) -> list:
        """
        Submit many programs to the queue with a progress bar (counts jobs submitted).

        The last submitted program becomes current_program (serializable).
        """
        self._require_qm()
        show_bar = bool(show_submit_progress) and _logger.isEnabledFor(logging.INFO)
        cm = self.quiet_external_logs() if quiet else contextlib.nullcontext()

        pendings = []
        with cm, tqdm(total=len(programs), desc=desc, disable=not show_bar, leave=True) as bar:
            for prog in programs:
                # queue_submit already remembers prog + cfg snapshot
                pending = self.queue_submit(prog, to_start=to_start, quiet=False)  # quiet handled by outer `cm`
                pendings.append(pending)
                bar.update(1)

        return pendings

    # ───────────────────────── convenience: submit + run with two bars ─────────────────────────
    def queue_submit_and_run_many(
        self,
        programs,
        *,
        n_totals: int | list[int],
        to_start: bool = False,
        processors: list | None = None,
        progress_handle: str = "iteration",
        show_submit_progress: bool = True,
        show_total_progress: bool = True,
        quiet: bool = True,
        submit_desc: str = "Submitting to queue...",
        run_desc: str = "Running queued...",
        print_report: bool = False,
        auto_job_halt: bool = True,
        sleep_s: float = 0.05,
        **proc_kwargs,
    ) -> list["RunResult"]:
        """
        - Shows a submission progress bar while pushing jobs to the queue
        - Then shows a global execution progress bar while jobs run
        """
        pendings = self.queue_submit_many_with_progress(
            programs,
            to_start=to_start,
            quiet=quiet,
            show_submit_progress=show_submit_progress,
            desc=submit_desc,
        )

        return self.queue_run_many(
            pendings,
            n_totals=n_totals,
            processors=processors,
            progress_handle=progress_handle,
            show_total_progress=show_total_progress,
            print_report=print_report,
            auto_job_halt=auto_job_halt,
            quiet=quiet,
            desc=run_desc,
            sleep_s=sleep_s,
            **proc_kwargs,
        )
