from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from ..calibration import CalibrationProposal, CalibrationSnapshot


@dataclass(frozen=True)
class ExecutionRequest:
    """Frozen run specification for later remote/persistent execution support."""

    kind: str
    template: str
    targets: dict[str, str] = field(default_factory=dict)
    params: dict[str, Any] = field(default_factory=dict)
    sequence: Any = None
    circuit: Any = None
    sweep: Any = None
    acquisition: Any = None
    shots: int | None = None
    analysis: str | None = None
    execute: bool = True
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class ExperimentResult:
    request: ExecutionRequest
    build: Any = None
    run: Any = None
    analysis: Any = None
    calibration_snapshot: CalibrationSnapshot | None = None
    artifact_path: str | None = None
    compiler_report: dict[str, Any] = field(default_factory=dict)
    plotter: Any = None
    source: Any = None

    def plot(self, *args, **kwargs):
        if self.plotter is None:
            raise RuntimeError("This result does not expose a plotter.")
        return self.plotter(*args, **kwargs)

    def inspect(self) -> dict[str, Any]:
        return {
            "request": self.request,
            "build": self.build,
            "analysis": self.analysis,
            "artifact_path": self.artifact_path,
            "compiler_report": self.compiler_report,
            "calibration_snapshot": self.calibration_snapshot,
        }

    def proposal(self) -> CalibrationProposal | None:
        metadata = dict(getattr(self.analysis, "metadata", {}) or {})
        updates = list(metadata.get("proposed_patch_ops") or [])
        if not updates:
            return None
        return CalibrationProposal(
            updates=updates,
            reason=f"Proposal generated by {self.request.template}",
        )
