"""
ConfigEngine: hardware config loading, saving, patching, and QM-config building.

Extracted from QuaProgramManager to separate config concerns from hardware control.
"""
from __future__ import annotations

import json
import logging
import threading
from copy import deepcopy
from pathlib import Path
from typing import Any, Callable

from octave_sdk import RFOutputMode

from ..core.errors import ConfigError
from ..core.utils import (
    deep_merge,
    json_dump,
    key_like,
    get_nested,
    numeric_keys_to_ints,
    require,
    select_keys,
)

_logger = logging.getLogger(__name__)

# QM config keys (full schema)
QM_TOPLEVEL_WHITELIST: set[str] = {
    "controllers", "elements", "octaves",
    "mixers", "waveforms", "digital_waveforms",
    "integration_weights", "oscillators", "pulses",
}

# Hardware.json skeleton keys (persisted truth)
HARDWARE_TOPLEVEL_KEYS: set[str] = {
    "version", "controllers", "octaves", "elements",
}

# Keys generated by PulseOperationManager
PULSE_KEYS: set[str] = {
    "pulses", "waveforms", "digital_waveforms",
    "integration_weights", "mixers", "oscillators",
}

# Extras persisted alongside hardware.json
HARDWARE_EXTRAS_KEYS_DEFAULT: set[str] = {"octave_links", "__qubox"}

# JSON mode map for octave output modes
JSON_MODE_MAP = {
    RFOutputMode.on: "always_on",
    RFOutputMode.off: "always_off",
    RFOutputMode.trig_normal: "triggered",
    RFOutputMode.trig_inverse: "triggered_reversed",
    RFOutputMode.debug: "always_off",
}


def _filter_qm_schema(d: dict) -> dict:
    return {k: deepcopy(v) for k, v in d.items() if k in QM_TOPLEVEL_WHITELIST}


def _filter_hardware_schema(d: dict) -> dict:
    return {k: deepcopy(v) for k, v in d.items() if k in HARDWARE_TOPLEVEL_KEYS}


def _patch_octave_output_modes(cfg: dict, mode: RFOutputMode) -> None:
    str_mode = JSON_MODE_MAP[mode]
    for _name, oct_data in (cfg.get("octaves") or {}).items():
        rf_outs = oct_data.get("RF_outputs") or {}
        for _ch, ch_data in rf_outs.items():
            if isinstance(ch_data, dict):
                ch_data["output_mode"] = str_mode


class ConfigEngine:
    """
    Manages the layered QM configuration:

    Layers (bottom to top):
        1. hardware_base   — persisted hardware.json skeleton
        2. hardware_extras — __qubox, octave_links (persisted alongside hardware)
        3. pulse_overlay   — generated by PulseOperationManager
        4. element_ops_overlay — element→operation mappings from POM
        5. runtime_overrides   — ephemeral patches (not persisted)

    Call build_qm_config() to merge all layers into a single dict
    suitable for QuantumMachinesManager.open_qm().
    """

    def __init__(
        self,
        hardware_path: str | Path | None = None,
        *,
        hardware_extras_keys: set[str] | None = None,
        override_octave_json_mode: RFOutputMode | None = None,
    ):
        self._lock = threading.RLock()
        self.hardware_path: Path | None = Path(hardware_path) if hardware_path else None
        self._hardware_extras_keys = set(
            HARDWARE_EXTRAS_KEYS_DEFAULT if hardware_extras_keys is None else hardware_extras_keys
        )

        # Layered state
        self.hardware_base: dict | None = None
        self.hardware_extras: dict = {}
        self.pulse_overlay: dict = {}
        self.element_ops_overlay: dict = {}
        self.runtime_overrides: dict = {}

        self._override_octave_json_mode = override_octave_json_mode
        self._dirty: dict[str, bool] = {"hardware": False, "pulses": False, "runtime": False}

        # Load immediately if path provided
        if self.hardware_path:
            self.load_hardware(self.hardware_path)

    # ─── Hardware I/O ─────────────────────────────────────────────
    def load_hardware(self, path: str | Path | None = None) -> None:
        hp = Path(path) if path else None
        if hp is not None:
            self.hardware_path = hp

        self.hardware_base = None
        self.hardware_extras = {}
        self._dirty["hardware"] = False

        if not self.hardware_path or not self.hardware_path.exists():
            _logger.info("No hardware file provided/found; continuing without hardware.")
            return

        try:
            raw = numeric_keys_to_ints(json.loads(self.hardware_path.read_text(encoding="utf-8-sig")))
        except json.JSONDecodeError as e:
            raise ValueError(
                f"Malformed hardware JSON at {self.hardware_path}: {e}"
            ) from e
        self.hardware_base = _filter_hardware_schema(raw)
        self.hardware_extras = select_keys(raw, self._hardware_extras_keys)
        _logger.info("Hardware loaded from %s", self.hardware_path)

    @property
    def wiring_rev(self) -> str | None:
        """SHA-256 first 8 hex chars of hardware.json content, or None."""
        if self.hardware_path is None or not self.hardware_path.exists():
            return None
        from ..core.experiment_context import ExperimentContext
        return ExperimentContext.compute_wiring_rev(self.hardware_path)

    @property
    def hardware(self) -> "HardwareConfig":
        """Return a typed ``HardwareConfig`` from the loaded layers.

        Merges ``hardware_base`` and ``hardware_extras`` and parses
        them through the Pydantic model.  Used by the binding system
        to derive ``ExperimentBindings``.
        """
        from ..core.config import HardwareConfig
        require(self.hardware_base is not None, "No hardware loaded.", ConfigError)
        merged = {**self.hardware_base, **self.hardware_extras}
        return HardwareConfig.from_dict(merged)

    def save_hardware(self, path: str | Path | None = None) -> None:
        require(self.hardware_base is not None, "No hardware loaded to save.", ConfigError)
        dst = Path(path) if path else (self.hardware_path or Path("hardware.json"))
        to_write = {**deepcopy(self.hardware_base), **deepcopy(self.hardware_extras)}
        dst.write_text(json_dump(to_write, indent=2), encoding="utf-8")
        _logger.info("Hardware saved → %s", dst)
        self._dirty["hardware"] = False

    # ─── Layered build ────────────────────────────────────────────
    def build_qm_config(self) -> dict:
        """Merge all layers into a single QM-compatible config dict."""
        require(self.hardware_base is not None, "No hardware loaded; cannot build QM config.", ConfigError)

        cfg = deepcopy(self.hardware_base)

        # Merge pulse overlay (deep merge, consistent with other layers)
        if self.pulse_overlay:
            cfg = deep_merge(cfg, deepcopy(self.pulse_overlay))

        # Merge element operations overlay (deep merge)
        if self.element_ops_overlay:
            cfg = deep_merge(cfg, self.element_ops_overlay)

        # Runtime overrides (deep merge)
        if self.runtime_overrides:
            cfg = deep_merge(cfg, self.runtime_overrides)

        cfg = numeric_keys_to_ints(cfg)
        cfg = _filter_qm_schema(cfg)

        if self._override_octave_json_mode is not None:
            _patch_octave_output_modes(cfg, self._override_octave_json_mode)

        return cfg

    # ─── Patching ─────────────────────────────────────────────────
    def patch_hardware(self, patch_fn: Callable[[dict, dict], None]) -> None:
        """
        Apply an in-place mutation to hardware_base and hardware_extras.
        Does NOT auto-burn or auto-save — caller decides.
        """
        require(self.hardware_base is not None, "No hardware loaded; cannot patch.", ConfigError)
        require(callable(patch_fn), "patch_fn must be callable")
        patch_fn(self.hardware_base, self.hardware_extras)
        self._dirty["hardware"] = True

    def patch_runtime(self, overrides: dict) -> None:
        """Deep-merge ephemeral overrides (not persisted)."""
        require(isinstance(overrides, dict), "overrides must be a dict")
        self.runtime_overrides = deep_merge(self.runtime_overrides, overrides)
        self._dirty["runtime"] = True

    def clear_runtime_overrides(self) -> None:
        self.runtime_overrides = {}
        self._dirty["runtime"] = False

    # ─── Pulse merger ─────────────────────────────────────────────
    def merge_pulses(self, pom, *, include_volatile: bool = True) -> None:
        """
        Generate pulse overlay from a PulseOperationManager.
        Also captures element operations as a deep-merge patch.
        """
        require(self.hardware_base is not None, "Hardware unknown; call load_hardware().", ConfigError)

        cfg = deepcopy(self.hardware_base)
        pom.burn_to_config(cfg, include_volatile=include_volatile)

        self.pulse_overlay = {k: deepcopy(cfg.get(k, {})) for k in PULSE_KEYS}

        elems = cfg.get("elements") or {}
        base_elements = set((self.hardware_base.get("elements") or {}).keys())
        ops_patch: dict = {}
        for el, el_cfg in elems.items():
            if not isinstance(el_cfg, dict):
                continue
            if str(el).startswith("__"):
                continue
            if el not in base_elements:
                _logger.warning(
                    "Skipping pulse operation overlay for non-hardware element '%s'",
                    el,
                )
                continue
            ops = el_cfg.get("operations")
            if isinstance(ops, dict) and ops:
                ops_patch.setdefault(el, {})["operations"] = deepcopy(ops)

        self.element_ops_overlay = {"elements": ops_patch} if ops_patch else {}
        self._dirty["pulses"] = True
        _logger.info("Pulses merged into pulse_overlay")

    # ─── Hardware setters (persisted) ─────────────────────────────
    def hw_set_octave_rf_output(
        self,
        *,
        octave: str,
        rf_out: int,
        lo_frequency: float | None = None,
        lo_source: str | None = None,
        output_mode: str | None = None,
        gain: float | None = None,
    ) -> None:
        """Update an octave RF output in the persisted hardware config."""
        def _patch(hw: dict, extras: dict):
            octaves = hw.setdefault("octaves", {})
            octd = octaves.setdefault(octave, {})
            rf_outs = octd.setdefault("RF_outputs", {})
            k = key_like(rf_outs, rf_out)
            if k not in rf_outs:
                rf_outs[k] = {}
            ch = rf_outs[k]
            if lo_frequency is not None:
                ch["LO_frequency"] = float(lo_frequency)
            if lo_source is not None:
                ch["LO_source"] = str(lo_source)
            if output_mode is not None:
                ch["output_mode"] = str(output_mode)
            if gain is not None:
                ch["gain"] = float(gain)

        self.patch_hardware(_patch)

    def hw_set_element_time_of_flight(self, *, element: str, time_of_flight: int) -> None:
        """Update time_of_flight for an element."""
        def _patch(hw: dict, extras: dict):
            elems = hw.setdefault("elements", {})
            require(element in elems, f"Unknown element '{element}'", ConfigError)
            elems[element]["time_of_flight"] = int(time_of_flight)
        self.patch_hardware(_patch)

    def hw_set_element_intermediate_frequency(self, *, element: str, intermediate_frequency: float) -> None:
        """Update intermediate_frequency for an element."""
        def _patch(hw: dict, extras: dict):
            elems = hw.setdefault("elements", {})
            require(element in elems, f"Unknown element '{element}'", ConfigError)
            elems[element]["intermediate_frequency"] = float(intermediate_frequency)
        self.patch_hardware(_patch)

    def hw_set_controller_io_offsets(
        self,
        *,
        controller: str,
        analog_outputs: dict[int, float] | None = None,
        analog_inputs: dict[int, float] | None = None,
    ) -> None:
        """Bulk-set controller analog IO offsets."""
        ao_map = dict(analog_outputs or {})
        ai_map = dict(analog_inputs or {})

        def _patch(hw: dict, extras: dict):
            ctrls = hw.setdefault("controllers", {})
            require(controller in ctrls, f"Unknown controller '{controller}'", ConfigError)
            cdict = ctrls[controller]

            if ao_map:
                aouts = cdict.setdefault("analog_outputs", {})
                for p, off in ao_map.items():
                    k = key_like(aouts, int(p))
                    if k not in aouts:
                        aouts[k] = {}
                    aouts[k]["offset"] = float(off)

            if ai_map:
                ains = cdict.setdefault("analog_inputs", {})
                for p, off in ai_map.items():
                    k = key_like(ains, int(p))
                    if k not in ains:
                        ains[k] = {}
                    ains[k]["offset"] = float(off)

        self.patch_hardware(_patch)

    # ─── Element info ─────────────────────────────────────────────
    def get_element_names(self, qm_config: dict | None = None) -> list[str]:
        """Return element names from the current or provided config."""
        cfg = qm_config or self.build_qm_config()
        return [e for e in (cfg.get("elements") or {}) if not e.startswith("__")]
